import streamlit as st
from st_pages import add_page_title, get_nav_from_toml
import base64
from streamlit_modal import Modal
from streamlit.components.v1 import html

def main():
    st.set_page_config(page_title="HerSpace", page_icon=":cherry_blossom:", layout="centered", initial_sidebar_state="auto", menu_items=None)
    load_css("static/css/main.css")
    set_background()

    nav = get_nav_from_toml(".streamlit/pages.toml")
    pg = st.navigation(nav)
    add_page_title(pg)
    pg.run()
    render_audio_player()
    set_footer()
    show_terms_of_use()

def load_css(file_path):
    with open(file_path, "r") as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

def set_background():
    bin_str = get_base64_of_bin_file('static/images/background.png')
    
    st.markdown(f"""
        <style>
        [data-testid="stAppViewContainer"] {{
            background-image: url("data:image/jpg;base64,{bin_str}");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }}
        
        .pink-title {{
            color: #000000;
            text-align: center;
            font-size: 20px;
            font-weight: bold;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.1);
            padding: 10px;
        }}
        </style>
        """, unsafe_allow_html=True)


def set_footer():
    st.markdown(
        """
        <div class="footer">
            <p style="margin: 0; font-size: 14px; color: #555;">
                Proudly participating in the She Builds AI Hackathon
            </p>
            <p style="margin: 0; font-size: 14px; color: #555;">
                Created with love by <a href="https://www.linkedin.com/in/h-b-y-5ab204198/" 
                    class="yellow-link">Hongbo</a> and <a href="https://www.linkedin.com/in/dt-333635ab/" 
                    class="yellow-link">Daitao</a>❤️ ©️ 2024
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )

def render_audio_player():
    audio_files = {
        "Calm Piano": "static/audio/calm_piano.wav",
        "Nature Sounds": "static/audio/nature_music.wav",
    }

    # Add audio selection and player at the bottom of sidebar
    with st.sidebar:
        st.markdown("<br>" * 4, unsafe_allow_html=True)

        st.image("static/images/recorder.png", use_container_width=True)
        
        selected_audio = st.selectbox(
            "🎵 Select Music Generated by Google MusicFx:",
            options=list(audio_files.keys()),
            index=0,
            key="background_music_selectbox"
        )
        
        audio_path = audio_files[selected_audio]
        st.audio(audio_path, format="audio/wav")


# Extract background setting code into separate function
def get_base64_of_bin_file(png_file):
    with open(png_file, 'rb') as f:
        data = f.read()
    return base64.b64encode(data).decode()


def show_terms_of_use():
    """
    Display the Terms of Use modal for HerSpace AI
    Ensures users understand AI limitations and their responsibilities
    """
    modal = Modal(key='HerSpace', title="Terms of Use - HerSpace", padding=50, max_width=700)

    if 'popup_closed' not in st.session_state:
        st.session_state.popup_closed = False

    if not st.session_state.popup_closed:
        with modal.container():
            st.markdown("""
            <div style="height: 15px; overflow-y: scroll; padding-right: 10px; margin-bottom: 10px;">
            """, unsafe_allow_html=True)
            
            st.markdown(
                '>**Welcome to HerSpace AI**, where women\'s empowerment and AI solutions unite. By accessing and using this platform, you acknowledge and agree to the following terms:')
            
            st.markdown('### 🤖 AI Limitations Acknowledgment')
            st.markdown("""
            HerSpace AI is powered by Google Gemini Pro that, while sophisticated, are not infallible. We transparently acknowledge that our AI may:
            - Generate responses that can contain inaccuracies or fictional information
            - Produce content that might seem coherent but lacks real-world verification
            - Potentially misinterpret complex or nuanced queries
            """)
            
            st.markdown('### 👥 User Responsibility')
            st.markdown("""
            By using HerSpace AI, you explicitly understand and agree that:
            - We encourage you to obscure any personal details during your interactions with the website. Please avoid sharing sensitive information.
            - You should not rely solely on AI-generated advice for critical decisions.
            - Professional human consultation is recommended for serious personal, medical, legal, or financial matters.
            """)
            
            st.markdown('### 🧠 Content Interpretation')
            st.markdown("""
            Our AI strives to provide helpful, empathetic, and constructive responses. However, users must:
            - Exercise critical thinking when interpreting AI-generated content
            - Understand that AI responses are generated based on probabilistic models
            - Recognize potential biases or limitations in the AI's knowledge base
            """)
            
            st.markdown('### 🛡️ Ethical Use')
            st.markdown("""
            HerSpace AI is designed to support and empower. Users are expected to:
            - Use the platform respectfully and constructively
            - Not exploit the AI for harmful, discriminatory, or malicious purposes
            - Protect their personal information during interactions
            """)
            
            st.markdown('### ⚖️ Liability Disclaimer')
            st.markdown("""
            HerSpace AI and its developers:
            - Disclaim all warranties, express or implied
            - Are not responsible for any decisions made based on AI interactions
            - Reserve the right to modify, suspend, or discontinue the service
            """)
            
            st.markdown('### 🔄 Continuous Improvement')
            st.markdown("""
            We are committed to:
            - Continuously refining our AI models
            - Implementing feedback to enhance accuracy and reliability
            - Maintaining transparency about our AI's capabilities and limitations
            """)
            
            st.markdown('</div>', unsafe_allow_html=True)
            
            accepted = st.checkbox("I have read, understood, and voluntarily accept these terms.")
            
            if accepted:
                close = st.button('Accept and Continue')
                st.session_state.popup_closed = True


if __name__ == "__main__":
    main()